[PHP]
memory_limit = 512M
error_reporting = E_ALL
display_errors = On
display_startup_errors = On

[xdebug]
xdebug.mode = develop,debug,coverage
xdebug.start_with_request = trigger
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.log_level = 0
